version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sqlite_db:/app/instance
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development

volumes:
  sqlite_db:
